# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: workers 
  become: yes

  tasks:

- name: Call Roles 2
  hosts: workers 
  roles:
   - hostname
   #- firewalld
   #- ntp-config
   #- motd
