# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 10.0.0.2
  become: yes

  tasks:

- name: Call Roles
  hosts: 10.0.0.2
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
