---
- name: set new variable
  set_fact:
    new_variable: awx_var_2
    cacheable: yes

- name: Filter and return only selected facts
  debug:
    msg:
      - " dist : {{ ansible_distribution }} ,  var set as a fact  : {{ new_variable }} "
      - " tower_job_template_id : {{ tower_job_template_id }}  , tower_user_email:  {{ tower_user_email }} "  
 
- name: Execute Telnet command and store output in fact
  become: true
  shell: |
    output=$(echo -e "open {{ your_telnet_host }} {{ your_telnet_port }} \nwait 1\nquit" | telnet)
    echo "Telnet output: $output"
  register: telnet_output

- name: Store Telnet output in fact
  set_fact:
    telnet_output: "{{ telnet_output.stdout_lines[-1] }}"    
    telnet_output_connection: "{{ telnet_output.stdout_lines[1] }}"     

    cacheable: yes
    
- name: Filter and store facts
  set_fact:
    filtered_facts:
      hostname: "{{ ansible_hostname }}"
      os: "{{ ansible_distribution }}"
      cpu_count: "{{ ansible_processor_count }}"
      memory_mb: "{{ ansible_memory_mb['real']['total'] }}"
        


- name: Generate report
  set_fact:
    report: |
      Facts for {{ inventory_hostname }}:
      var set as a fact  : {{ new_variable }}
      telnet connection status  : {{ telnet_output_connection }}
      Hostname: {{ filtered_facts.hostname }}
      Operating System: {{ filtered_facts.os }}
      CPU Count: {{ filtered_facts.cpu_count }}
      Memory: {{ filtered_facts.memory_mb }} MB

- name: Where am i 
  shell: pwd

- name: Write report to file
  copy:
    content: "{{ report }}"
    dest: "~/ansible/report_{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}.txt"


    backup: yes

- name: Fetch report from remote machine
  fetch:
    src: "~/ansible/report_{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}.txt"
    dest: "/home/user1/"
    flat: yes
    fail_on_missing: yes

    


 

