---
# tasks file for /etc/ansible/roles/motd
#- name: set motd
 # become: yes
  #template:
  #  src: files/motd.j2
  #  dest: /etc/motd
  #  owner: root
  #  group: root
  #  mode: 0444
- name: set new variable
  set_fact:
    new_variable: amine
    cacheable: yes

  
- name: Filter and return only selected facts
  debug:
    vars:
      - 'ansible_distribution'
      - 'new_variable'
      - 'inventory_dir'
      - 'inventory_file' 
      - 'inventory_hostname_short'
      - 'playbook_dir' 
      - 'tower_inventory_id' 
      - 'tower_inventory_name' 
      - 'tower_job_id'
      - 'tower_job_launch_type'
      - 'tower_job_template_id'
      - 'tower_job_template_name' 
      - 'tower_project_scm_branch'   
      - 'tower_user_email'  
      - 'tower_user_first_name'
      - 'tower_user_id'
      - 'tower_user_last_name' 
      - 'tower_user_name' 
