---
- name: set new variable
  set_fact:
    new_variable: awx_var_2
    cacheable: yes

- name: Filter and return only selected facts
  debug:
    msg:
      - " dist : {{ ansible_distribution }} ,  var set as a fact  : {{ new_variable }} "
      - " tower_job_template_id : {{ tower_job_template_id }}  , tower_user_email:  {{ tower_user_email }} "  

- name: Filter and store facts
  set_fact:
    filtered_facts:
      hostname: "{{ ansible_hostname }}"
      os: "{{ ansible_distribution }}"
      cpu_count: "{{ ansible_processor_count }}"
      memory_mb: "{{ ansible_memory_mb['real']['total'] }}"

- name: Generate report
  set_fact:
    report: |
      Facts for {{ inventory_hostname }}:
      var set as a fact  : {{ new_variable }}
      Hostname: {{ filtered_facts.hostname }}
      Operating System: {{ filtered_facts.os }}
      CPU Count: {{ filtered_facts.cpu_count }}
      Memory: {{ filtered_facts.memory_mb }} MB

- name: Where am i 
  shell: pwd

- name: Write report to file
  copy:
    content: "{{ report }}"
    dest: "~/ansible/report2.txt"

- name: Fetch report from remote machine
  fetch:
    src: "~/ansible/report2.txt"
    dest: "/var/lib/awx/projects/_11__project_awx/report-{{ inventory_hostname }}"
    flat: yes
    fail_on_missing: yes

    


 

