---
# tasks file for /etc/ansible/roles/motd
#- name: set motd
 # become: yes
  #template:
  #  src: files/motd.j2
  #  dest: /etc/motd
  #  owner: root
  #  group: root
  #  mode: 0444
- name: Install Telnet package
    yum:
      name: telnet
      state: present
- name: Start Telnet service
    service:
      name: telnet
      state: started
