---
# tasks file for /etc/ansible/roles/motd
#- name: set motd
 # become: yes
  #template:
  #  src: files/motd.j2
  #  dest: /etc/motd
  #  owner: root
  #  group: root
  #  mode: 0444
- name: Install the provided package
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items:
  - telnet
  - telnet-server

- name: Start Telnet service
  systemd:
    name: telnet
    state: started
