---
# tasks file for /etc/ansible/roles/motd
#- name: set motd
 # become: yes
  #template:
  #  src: files/motd.j2
  #  dest: /etc/motd
  #  owner: root
  #  group: root
  #  mode: 0444
- name: set new variable
  set_fact:
    new_variable: amine
    cacheable: yes

  
- name: Filter and return only selected facts
  debug:
    msg:
      - " dist : {{ ansible_distribution }} ,  var  : {{ new_variable }} "

