---
- name: Create a directory and give it all permissions
  file:
    path: /root/reports
    state: directory
    mode: "0777"
  delegate_to: localhost
  connection: local
  vars:
    ansible_fetch_directory: /tmp/fetched_files
  debug:
    var: ansible_fetch_result
  

