---
- name: Create a directory and give it all permissions
  file:
    path: /root/reports
    state: directory
    mode: "0777"
  delegate_to: localhost
  connection: local
  
- name: Fetch report from remote machine
  become: yes
  fetch:
   # src: "/root/ansible/report_{{ ansible_hostname }}_{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}.txt"
    src: "/root/ansible/report_worker1_2023-03-06_01-52.txt"
    dest: "/root/report/"
    flat: yes
    fail_on_missing: yes
    #delegate_to: workers
  delegate_to: localhost
  connection: local
