- name: Fetch report from remote machinee
  fetch:
    src: "/root/ansible/report_worker1_2023-03-06_01-52.txt"
    dest: "/root/report/"
    flat: yes
    fail_on_missing: yes
  delegate_to: localhost
  connection: local

